### ISSUE TITLE
Internal Server Error (HTTP 500) when accessing docs

### ISSUE THREAD

**Issue by ion-oset** [TrustTheVote-Project/VersaEDM-Backend#14]
I didn't dig into what causes the error but I bisected the history and it first appears in 6534a760
I've had a similar error that was caused by using a class when an instance was expected. (The actual function parameter, not the decorator). This seems like the reverse.

---

HTTP request: `GET /openapi.json`
Exception:

```
Traceback (most recent call last):
  File "versadm/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptoo
ls_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "versadm/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_heade
rs.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "versadm/.venv/lib/python3.8/site-packages/fastapi/applications.py", line
 208, in __call__
    await super().__call__(scope, receive, send)
  File "versadm/.venv/lib/python3.8/site-packages/starlette/applications.py", li
ne 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "versadm/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py
", line 181, in __call__
    raise exc from None
  File "versadm/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py
", line 159, in __call__
    await self.app(scope, receive, _send)
  File "versadm/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line
 82, in __call__
    raise exc from None
  File "versadm/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line
 71, in __call__
    await self.app(scope, receive, sender)
  File "versadm/.venv/lib/python3.8/site-packages/starlette/routing.py", line 58
0, in __call__
    await route.handle(scope, receive, send)
  File "versadm/.venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "versadm/.venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "versadm/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 161, in openapi
    return JSONResponse(self.openapi())
  File "versadm/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 136, in openapi
    self.openapi_schema = get_openapi(
  File "versadm/.venv/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 387, in get_openapi
    definitions = get_model_definitions(
  File "versadm/.venv/lib/python3.8/site-packages/fastapi/utils.py", line 24, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 842, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 440, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 773, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 667, in pydantic.schema.field_singleton_sub_fields_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 842, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 440, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 773, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 667, in pydantic.schema.field_singleton_sub_fields_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 773, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 679, in pydantic.schema.field_singleton_sub_fields_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 839, in pydantic.schema.field_singleton_schema
  File "/usr/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

**Comment by ion-oset** [comment]
The problem is caused by Pydantic not automatically recognizing forward references to types. It needs to be an explicit call on the class. See [Pydantic Manual: Postponed annotations](https://pydantic-docs.helpmanual.io/usage/postponed_annotations/). PR forthcoming.

For future reference: everything in the above stack trace that says "`File "pydantic/schema.py`" can't be debugged with PDB because Pydantic gets [installed as the Cython compiled version](https://pydantic-docs.helpmanual.io/install/#compiled-with-cython) by default. It's possible to set breakpoints by [setting up the Cython debugger](https://cython.readthedocs.io/en/stable/src/userguide/debugging.html). I didn't have time to do that, but it would be part of the right answer as the code gets too complex for the quick & dirty way I settled for:

- [Comment out the routers in `create_app`](https://github.com/TrustTheVote-Project/VersaEDM-Backend/commit/ac12c382). This led to `routers.election.create_router` and `routers.election_report.create_router` as the routes that were failing.
- Commented out the fields in [`election.py`](https://github.com/TrustTheVote-Project/VersaEDM-Backend/blob/ac12c382/src/electos/versadm/models/nist/classes/election.py) and [`election_report.py`](https://github.com/TrustTheVote-Project/VersaEDM-Backend/blob/ac12c382/src/electos/versadm/models/nist/classes/election_report.py) which led to the fields whose types had forward references.
